### ISSUE TITLE
Trying to use module

### ISSUE THREAD

**Issue by rhanb** [wwwalkerrun/nativescript-ngx-magic#2]
Hello,

I wanted to try this new repo, but I've got some issues:

- `npm i npm i @wwwalkerrun/nativescript-ngx-magic --save` doesn't work
- path issues in install.js, for example: 
`var hasNativeScript = fs.existsSync("../../../../nativescript");` 
instead of
 `var hasNativeScript = fs.existsSync("../../nativescript");`
- Same for the `package.json`, so the package.json from the root folder of the project doesn't update
- Problem wwhen testing: can't pass if it's not in a nativescript-app, the repo shouldn't provide a full nativescript app to launch tests? example: `expect(MagicService.IS_NATIVESCRIPT()).toBe(true);` is always false

cheers

**Comment by NathanWalker** [comment]
Hi @rhanbIT - when you say `npm i @wwwalkerrun/nativescript-ngx-magic --save` doesn't work - I assume you are trying that in a new angular-cli project, not in this repo correct?

The path issues you mentioned are only valid when installed correctly in a valid angular-cli project.

The testing is wip on this repo at moment.

**Comment by rhanb** [comment]
Hi @NathanWalker ,

Actually yesterday when i was trying `npm i @wwwalkerrun/nativescript-ngx-magic --save`, i got a 404 error. 

The paths were wrong for a new angular-cli project because I published a temp module (because of the 404 error) but without the @wwwalkerrun parent folder, my bad.. 

Thanks for your answer :)
