### ISSUE TITLE
Trouble with Paths, Part Deux

### ISSUE THREAD

**Issue by shyamseshadri** [wwwalkerrun/nativescript-ngx-magic#7]
I looked at https://github.com/wwwalkerrun/nativescript-ngx-magic/issues/4, and the README, and I'm still having issues with paths.
I keep getting

`Error: File /data/data/org.nativescript.nativescript/files/app/home.component.tns.html does not exist. Resolved from: home.component.tns.html.`

This is after:
1.) Created a separate app.module, which loads all my components
2.) Switched all components to use Component from

`import { Component } from '@wwwalkerrun/nativescript-ngx-magic';`

3.) Added moduleId: module.id to all the components.

The home.component.ts is actually in app/home/home/home.component.ts

4.) All paths have been changed to have relative paths, without the ./ at the beginning.

I'm at the point of banging my head against the wall, not sure what else I'm missing.

If I change all the paths to absolute from the app folder, it works, but of course breaks the web app in that case :(

I've pushed my project to Github [here](https://github.com/shyamseshadri/shyam-ng2-nativescript-testing)

Any help would be greatly appreciated, really looking forward to getting this working.

**Comment by NathanWalker** [comment]
You just have a small error right here:
https://github.com/shyamseshadri/shyam-ng2-nativescript-testing/blob/master/src/app/home/home/home.component.ts#L11

Should be moduleId, not module. Cheers 🍻

**Comment by shyamseshadri** [comment]
Mwahahaha, thanks a lot. I knew it was something stupid and obvious that I was missing :)

Thanks for the quick turnaround
